drop table if exists appointment;
drop table if exists time_slot;
drop table if exists service_price;
drop table if exists service;
drop table if exists pet;
drop table if exists client;
drop table if exists groomer;
drop table if exists breed;
drop table if exists species;
drop table if exists breed_type;


CREATE TABLE client (
                        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        first_name VARCHAR(50) NOT NULL,
                        last_name VARCHAR(50),
                        phone VARCHAR(18) NOT NULL UNIQUE,
                        email VARCHAR(100),
                        password VARCHAR(255) NOT NULL
);




CREATE TABLE groomer (
                         id bigint primary key generated by default as identity,
                         first_name VARCHAR(100) NOT NULL,
                         last_name VARCHAR(100) NOT NULL,
                         career_start DATE NOT NULL,
                         email VARCHAR(100) NOT NULL UNIQUE,
                         phone VARCHAR(20)
);

CREATE TYPE breed_type_enum AS ENUM ('SMALL', 'MEDIUM', 'LARGE');

CREATE TABLE breed (
                       id bigint primary key generated by default as identity,
                       name VARCHAR(50) NOT NULL,
                       breed_type breed_type_enum NOT NULL
);

CREATE TABLE pet (
                     id bigint primary key generated by default as identity,
                     name VARCHAR(50) NOT NULL,
                     species VARCHAR(10) NOT NULL check ( species = 'кошка' or species = 'собака' ),
                     breed_id bigint references breed (id),
                     birth_date DATE NOT NULL,
                     owner_id bigint NOT NULL REFERENCES client (id) ON DELETE CASCADE,
                    image_path varchar(256)
);


CREATE TABLE service (
                         id bigint primary key generated by default as identity,
                         name VARCHAR(50) NOT NULL,
                         description text
);

create table service_price (
                               id bigint primary key generated by default as identity,
                               service_id bigint NOT NULL REFERENCES service (id) ON DELETE CASCADE,
                               species VARCHAR(10) NOT NULL,
                               breed_type breed_type_enum,
                               price int not null check ( price > 0 )
);

create table time_slot (
                           id bigint primary key generated by default as identity ,
                           groomer_id bigint NOT NULL REFERENCES groomer (id) ON DELETE CASCADE,
                           start_time TIMESTAMP not null,
                           end_time TIMESTAMP not null,
                           taken bool default false
);

CREATE TABLE appointment (
                             id bigint primary key generated by default as identity,
                             pet_id bigint NOT NULL REFERENCES pet (id) ON DELETE CASCADE,
                             groomer_id bigint NOT NULL REFERENCES groomer (id) ON DELETE CASCADE,
                             service_id bigint not null REFERENCES service (id) ON DELETE CASCADE,
                             price bigint not null check ( price > 0),
                             date TIMESTAMP NOT NULL,
                             notes text
);
