drop table if exists appointment;
drop table if exists time_slot;
drop table if exists service_price;
drop table if exists service;
drop table if exists pet;
drop table if exists client;
drop table if exists groomer;
drop table if exists breed;
drop table if exists species;
drop table if exists breed_type;


CREATE TABLE client (
                        id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        first_name VARCHAR(50) NOT NULL,
                        last_name VARCHAR(50),
                        phone VARCHAR(18) NOT NULL UNIQUE,
                        password VARCHAR(255) NOT NULL
);




CREATE TABLE groomer (
                         id int primary key generated by default as identity ,
                         first_name VARCHAR(100) NOT NULL,
                         last_name VARCHAR(100) NOT NULL,
                         career_start DATE NOT NULL,
                         email VARCHAR(100) NOT NULL UNIQUE,
                         phone VARCHAR(20)
);
-- Таблица видов животных
CREATE TABLE species (
                         id int primary key generated by default as identity ,
                         name VARCHAR(50) NOT NULL UNIQUE
);

-- Таблица типов пород
CREATE TABLE breed_type (
                            id int primary key generated by default as identity ,
                            name VARCHAR(50) NOT NULL UNIQUE
);

-- Таблица пород
CREATE TABLE breed (
                       id int primary key generated by default as identity ,
                       name VARCHAR(50) NOT NULL,
                       species_id INT NOT NULL REFERENCES species(id),
                       breed_type_id INT REFERENCES breed_type(id)
);

-- Таблица питомцев
CREATE TABLE pet (
                     id int primary key generated by default as identity ,
                     name VARCHAR(50) NOT NULL,
                     species_id INT NOT NULL REFERENCES species(id),
                     breed_id INT REFERENCES breed(id),
                     birth_date DATE NOT NULL,
                     owner_id INT NOT NULL REFERENCES client(id) ON DELETE CASCADE
);

-- Таблица услуг
CREATE TABLE service (
                         id int primary key generated by default as identity ,
                         name VARCHAR(50) NOT NULL,
                         description TEXT
);

-- Таблица цен на услуги
CREATE TABLE service_price
(
    id           int primary key generated by default as identity ,
    service_id    INT NOT NULL REFERENCES service (id) ON DELETE CASCADE,
    species_id INT REFERENCES species(id),
    breed_id INT REFERENCES breed(id),
    breed_type_id INT REFERENCES breed_type(id),
    price         INT NOT NULL CHECK (price > 0)
);
create table time_slot (
                           id int primary key generated by default as identity ,
                           groomer_id INT NOT NULL REFERENCES groomer (id) ON DELETE CASCADE,
                           start_time TIMESTAMP not null,
                           end_time TIMESTAMP not null,
                           taken bool default false
);

CREATE TABLE appointment (
                             id int primary key generated by default as identity,
                             pet_id INT NOT NULL REFERENCES pet (id) ON DELETE CASCADE,
                             groomer_id INT NOT NULL REFERENCES groomer (id) ON DELETE CASCADE,
                             service_id int not null REFERENCES service (id) ON DELETE CASCADE,
                             price int not null check ( price > 0),
                             date TIMESTAMP NOT NULL,
                             notes text
);
